finddepsrow: add checks

diff --git a/finddepsrow b/finddepsrow
--- a/finddepsrow
+++ b/finddepsrow
@@ -14,6 +14,12 @@ if [ "$1" = "" ]; then
     exit 1
 fi
 
+# no options used with prtdepsfix
+if [[ $1 == -* ]]; then
+    echo -e "Invalid input "$1". Usage: finddepsrow <port>"
+    exit 1
+fi
+
 echo "** checking"
 
 found=$(finddeps ${1} | grep -v "core" | awk '{print $1}')
